gamesh:
  inverse_conic_enabled: true
  enable_suboptimal_policy: false
  suboptimal_method: 0
  w_1: 10.0
  w_2: 2.0
  w_3: 1.0
  prob_or_vote_threshold: 20.0
  max_distance_cam_feature: 40.0
  steiner_grid_step_length: 20.0
  steiner_grid_side_length: 280.0
  manifold_update_every: 1
  initial_manifold_update_skip: 2
<<<<<<< HEAD
  save_manifold_every: 32
=======
  save_manifold_every: 1
>>>>>>> 9ba05b471d2d8fdc18b062948bfd4d804d31fcd1
  primary_points_visibility_threshold: 1
  all_sort_of_output: false
  fake_points_multiplier: 0
  update_points_position: false
