gamesh:
  inverse_conic_enabled: true
  enable_suboptimal_policy: false
  suboptimal_method: 0
  update_points_position: false
  enable_ray_mistrust: false
  
  w_1: 10.0
  w_2: 2.0
  w_3: 1.0
  w_m: 1.0
  
  free_vote_threshold: 20.0
  ray_removal_threshold: 100000.0
  vertex_removal_threshold: 100000000.0
  
  num_points_per_camera: 15
  max_distance_cam_feature: 40.0
  steiner_grid_step_length: 20.0
  
  manifold_update_every: 1
  initial_manifold_update_skip: 2
  save_manifold_every: 1
  primary_points_visibility_threshold: 1
  
  all_sort_of_output: false
  time_stats_output: false
  
  output_folder: "/home/enrico/gamesh_output/"
  time_stats_folder: "/home/enrico/gamesh_stats/"
  count_stats_folder: "/home/enrico/gamesh_stats/"
